[package]
name = "ut61e"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
heapless = "^0.7.16"
hidapi = "^2.4.1"
onlyerror = "0.1.3"

[dev-dependencies]
cp211x_uart = { path = "../cp211x_uart" }
